directories:
  output: release
  buildResources: assets
appId: com.pixelpilot.app
productName: PixelPilot
files:
  - filter:
      - dist/**/*
      - electron/**/*
protocols:
  name: PixelPilot
  schemes:
    - pixelpilot
extraResources:
  - from: server
    to: server
    filter:
      - '**/*'
mac:
  category: public.app-category.developer-tools
win:
  target:
    - nsis
linux:
  target:
    - AppImage
electronVersion: 38.0.0
